//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAgentBot.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionSet
    {
        public int SetId { get; set; }
        public string SetName { get; set; }
        public string Description { get; set; }
        public System.DateTime created { get; set; }
    }
}
