//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAgentBot.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserAgentDBEntities : DbContext
    {
        public UserAgentDBEntities()
            : base("name=UserAgentDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerAgentLog> CustomerAgentLog { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<LogMessage> LogMessage { get; set; }
        public virtual DbSet<QuestionAnswer> QuestionAnswer { get; set; }
        public virtual DbSet<QuestionSet> QuestionSet { get; set; }
        public virtual DbSet<QuizUserLog> QuizUserLog { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<UserInformation> UserInformation { get; set; }
        public virtual DbSet<UserLog> UserLog { get; set; }
        public virtual DbSet<UserPendingRequest> UserPendingRequest { get; set; }
    }
}
